class DryController < ApplicationController
	
	def index
	  if session[:code].to_s.length == 4
	  	  @dry_sum = StandardDatum.find_by_sql ['select sum(dry_weight) from standard_data s where s.code like ?',"%"+session[:code].to_s+"%"]

	  	  @by_breed = DryTobacco.find_by_sql ["select trim(f.breed) as breed,sum(d.weight * p.packing_amount) as sum from dry_tobaccos d left join packings p on p.task_id = d.task_id left join fresh_tobaccos f on f.task_id = d.task_id left join tasks t on t.id = d.task_id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where c.code like ? group by trim(f.breed)","%"+session[:code].to_s+"%"]
		  @by_quality = DryTobacco.find_by_sql ["select sum(dd.weight_zz)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as zz,sum(dd.weight_wq)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as wq,sum(dd.weight_q)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as q,sum(dd.weight_zs)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as zs from dry_details dd left join dry_tobaccos d on d.id = dd.dry_tobacco_id left join packings p on p.task_id = d.task_id left join tasks t on t.id = d.task_id left join fresh_tobaccos f on f.task_id = t.id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where c.code like ?","%"+session[:code].to_s+"%"]
		  @by_part = DryTobacco.find_by_sql	["select trim(f.part) as part,sum(d.weight * p.packing_amount) as sum from dry_tobaccos d left join packings p on p.task_id = d.task_id left join fresh_tobaccos f on f.task_id = d.task_id left join tasks t on t.id = d.task_id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where c.code like ? group by trim(f.part)","%"+session[:code].to_s+"%"]
		  @by_breed_part = DryTobacco.find_by_sql ["select trim(f.breed) as breed,trim(f.part) as part,sum(d.weight * p.packing_amount) as sum from dry_tobaccos d left join packings p on p.task_id = d.task_id left join fresh_tobaccos f on f.task_id = d.task_id left join tasks t on t.id = d.task_id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where c.code like ? group by trim(f.breed),trim(f.part)","%"+session[:code].to_s+"%"]
		  @by_breed_quality = DryTobacco.find_by_sql ["select trim(f.breed) as breed,sum(dd.weight_zz)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as zz,sum(dd.weight_wq)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as wq,sum(dd.weight_q)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as q,sum(dd.weight_zs)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as zs from dry_details dd left join dry_tobaccos d on d.id = dd.dry_tobacco_id left join packings p on p.task_id = d.task_id left join tasks t on t.id = d.task_id left join fresh_tobaccos f on f.task_id = t.id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where c.code like ? group by trim(f.breed)","%"+session[:code].to_s+"%"]
		  @by_part_quality = DryTobacco.find_by_sql ["select trim(f.part) as part,sum(dd.weight_zz)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as zz,sum(dd.weight_wq)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as wq,sum(dd.weight_q)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as q,sum(dd.weight_zs)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as zs from dry_details dd left join dry_tobaccos d on d.id = dd.dry_tobacco_id left join packings p on p.task_id = d.task_id left join tasks t on t.id = d.task_id left join fresh_tobaccos f on f.task_id = t.id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where c.code like ? group by trim(f.part)","%"+session[:code].to_s+"%"]
		  @city_name = City.find_by_sql ['select c.title from cities c where c.code = ?',session[:code].to_s]
		  respond_to do |format|
		    format.html
		    format.json { render json:{ by_breed: @by_breed,
		    							by_quality: @by_quality,
		    							by_part: @by_part,
		    							by_breed_part: @by_breed_part,
		    							by_breed_quality: @by_breed_quality,
		    							by_part_quality: @by_part_quality,
		    							city_name: @city_name,
		    							dry_sum: @dry_sum }}
		  end
		elsif session[:code].to_s.length == 2
		  @dry_sum = StandardDatum.find_by_sql ['select sum(dry_weight) from standard_data s where s.code like ?',"%"+session[:code].to_s+"%"]

		  @by_breed = DryTobacco.find_by_sql ["select trim(f.breed) as breed,sum(d.weight * p.packing_amount) as sum from dry_tobaccos d left join packings p on p.task_id = d.task_id left join fresh_tobaccos f on f.task_id = d.task_id left join tasks t on t.id = d.task_id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id left join cities ci on ci.id = c.city_id where ci.code like ? group by trim(f.breed)","%"+session[:code].to_s+"%"]
		  @by_quality = DryTobacco.find_by_sql ["select sum(dd.weight_zz)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as zz,sum(dd.weight_wq)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as wq,sum(dd.weight_q)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as q,sum(dd.weight_zs)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as zs from dry_details dd left join dry_tobaccos d on d.id = dd.dry_tobacco_id left join packings p on p.task_id = d.task_id left join tasks t on t.id = d.task_id left join fresh_tobaccos f on f.task_id = t.id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where s.code like ?","%"+session[:code].to_s+"%"]
		  @by_part = DryTobacco.find_by_sql	["select trim(f.part) as part,sum(d.weight * p.packing_amount) as sum from dry_tobaccos d left join packings p on p.task_id = d.task_id left join fresh_tobaccos f on f.task_id = d.task_id left join tasks t on t.id = d.task_id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id left join cities ci on ci.id = c.city_id where ci.code like ? group by trim(f.part)","%"+session[:code].to_s+"%"]
		  @by_breed_part = DryTobacco.find_by_sql ["select trim(f.breed) as breed,trim(f.part) as part,sum(d.weight * p.packing_amount) as sum from dry_tobaccos d left join packings p on p.task_id = d.task_id left join fresh_tobaccos f on f.task_id = d.task_id left join tasks t on t.id = d.task_id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id left join cities ci on ci.id = c.city_id where ci.code like ? group by trim(f.breed),trim(f.part)","%"+session[:code].to_s+"%"]
		  @by_breed_quality = DryTobacco.find_by_sql ["select trim(f.breed) as breed,sum(dd.weight_zz)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as zz,sum(dd.weight_wq)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as wq,sum(dd.weight_q)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as q,sum(dd.weight_zs)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as zs from dry_details dd left join dry_tobaccos d on d.id = dd.dry_tobacco_id left join packings p on p.task_id = d.task_id left join tasks t on t.id = d.task_id left join fresh_tobaccos f on f.task_id = t.id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where s.code like ? group by trim(f.breed)","%"+session[:code].to_s+"%"]
		  #select trim(f.breed),sum(dd.weight_zz)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as zz,sum(dd.weight_wq)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as wq,sum(dd.weight_q)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as q,sum(dd.weight_zs)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as zs from dry_details dd left join dry_tobaccos d on d.id = dd.dry_tobacco_id left join packings p on p.task_id = d.task_id left join tasks t on t.id = d.task_id left join fresh_tobaccos f on f.task_id = t.id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where s.code like '%43%' group by trim(f.breed)
		  @by_part_quality = DryTobacco.find_by_sql ["select trim(f.part) as part,sum(dd.weight_zz)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as zz,sum(dd.weight_wq)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as wq,sum(dd.weight_q)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as q,sum(dd.weight_zs)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as zs from dry_details dd left join dry_tobaccos d on d.id = dd.dry_tobacco_id left join packings p on p.task_id = d.task_id left join tasks t on t.id = d.task_id left join fresh_tobaccos f on f.task_id = t.id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where s.code like ? group by trim(f.part)","%"+session[:code].to_s+"%"]
		  #select f.part,sum(dd.weight_zz)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as zz,sum(dd.weight_wq)/sum(amount_weight) * sum(d.weight * p.packing_amount)/3 as wq,sum(dd.weight_q)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as q,sum(dd.weight_zs)/sum(amount_weight) *sum(d.weight * p.packing_amount)/3 as zs from dry_details dd left join dry_tobaccos d on d.id = dd.dry_tobacco_id left join packings p on p.task_id = d.task_id left join tasks t on t.id = d.task_id left join fresh_tobaccos f on f.task_id = t.id left join rooms r on r.id = t.room_id left join stations s on s.id = r.station_id left join counties c on c.id = s.county_id where s.code like '%43%' group by f.part
		  respond_to do |format|
		    format.html
		    format.json { render json:{ by_breed: @by_breed,
		    							by_quality: @by_quality,
		    							by_part: @by_part,
		    							by_breed_part: @by_breed_part,
		    							by_breed_quality: @by_breed_quality,
		    							by_part_quality: @by_part_quality,
		    							dry_sum: @dry_sum }}
		  end
		end
		  	

	end
end
